robot:
  name: "Starfall-X"
  version: 1.0.0
  comms:
    port: "/dev/serial0"
    baud: 115200

ball:
  lab_mask:
    lower:
      L: 90
      A: 92
      B: 50
    upper:
      L: 180
      A: 145
      B: 119 
      
  roi:
    x1: 0
    y1: 0
    x2: 960
    y2: 300


goal:
  target_color: "BLUE"
  lab_mask_yellow:
    lower:
      L: 140
      A: 90
      B: 115
    upper:
      L: 255
      A: 105
      B: 140
  lab_mask_blue:
    lower:
      L: 150
      A: 120
      B: 200
    upper:
      L: 240
      A: 205
      B: 220
  roi:
    x1: 0
    y1: 0
    x2: 960
    y2: 300

line:
  lab_mask:
    lower:
      L: 160
      A: 120
      B: 140
    upper:
      L: 255
      A: 255
      B: 255
  roi:
    x1: 0
    y1: 400
    x2: 960
    y2: 500