robot:
  name: "Starfall-X"
  version: 1.0.0
  comms:
    port: "/dev/serial0"
    baud: 115200

ball:
  lab_mask:
    lower:
      L: 20
      A: 100
      B: 60
    upper:
      L: 195
      A: 150
      B: 105 
      
  roi:
    x1: 0
    y1: 0
    x2: 960
    y2: 540


goal:
  target_color: "YELLOW"
  lab_mask_yellow:
    lower:
      L: 80
      A: 30
      B: 95
    upper:
      L: 255
      A: 100
      B: 140
  lab_mask_blue:
    lower:
      L: 100
      A: 120
      B: 155
    upper:
      L: 240
      A: 225
      B: 220
  roi:
    x1: 0
    y1: 0
    x2: 960
    y2: 300

line:
  lab_mask:
    lower:
      L: 190
      A: 120
      B: 100
    upper:
      L: 255
      A: 255
      B: 255
  roi:
    x1: 0
    y1: 370
    x2: 960
    y2: 500